name: Powershell Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: PowerShell
      shell: powershell Out-Null
      run: echo "Hello world"
      
    - name: PowerShell Multiline
      shell: powershell
      run: |
        echo "1. Multiline shell steps works too"
        echo 2. Multiline shell TWOOO works too
        echo "3. Multiline shell THREE works too"
        mkdir pyFolder
  
    - name: Multi-line test
      shell: powershell
      run: |2
        echo "Multiline shell steps works too"
        Remove-Item 'pyFolder' -Recurse
        mkdir pyFolder
        ls
        $items = @('one','two','three')
        foreach ($item in $items)
        {
          echo $item
        }
